print("Masukan nama Anda : ")
namaDepan = input()
print("Masukan umur Anda : ")
umur = input()
alamat = input("Masukan alamat Anda : ")
prodi = input("Masukan Prodi Anda : ")

print("Nama Anda adalah " + namaDepan)
print("Umur Anda adalah " + umur)
print("Anda beralamat di " + alamat)
print("Prodi Anda " + prodi)